/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseEffectVsQueryIndexRouteImport } from './routes/useEffect-vs-query/index'
import { Route as SsrThreeWaysIndexRouteImport } from './routes/ssr-three-ways/index'
import { Route as PagesNLinksIndexRouteImport } from './routes/pages-n-links/index'
import { Route as UseEffectVsQueryUseQueryRouteImport } from './routes/useEffect-vs-query/use-query'
import { Route as UseEffectVsQueryUseEffectRouteImport } from './routes/useEffect-vs-query/use-effect'
import { Route as SsrThreeWaysSsrTrueRouteImport } from './routes/ssr-three-ways/ssr-true'
import { Route as SsrThreeWaysSsrFalseWorksRouteImport } from './routes/ssr-three-ways/ssr-false-works'
import { Route as SsrThreeWaysSsrFalseRouteImport } from './routes/ssr-three-ways/ssr-false'
import { Route as SsrThreeWaysSsrDataOnlyRouteImport } from './routes/ssr-three-ways/ssr-data-only'
import { Route as PagesNLinksSearchRouteImport } from './routes/pages-n-links/search'
import { Route as PagesNLinksNormalRouteImport } from './routes/pages-n-links.normal'
import { Route as PagesNLinksAppRouteRouteImport } from './routes/pages-n-links/app/route'
import { Route as PagesNLinksGroupedRouteRouteImport } from './routes/pages-n-links/_grouped/route'
import { Route as PagesNLinksAppIndexRouteImport } from './routes/pages-n-links/app/index'
import { Route as UseEffectVsQueryApiUsersRouteImport } from './routes/useEffect-vs-query/api/users'
import { Route as PagesNLinksParamsExampleIdRouteImport } from './routes/pages-n-links/params/$exampleId'
import { Route as PagesNLinksCatchallSplatRouteImport } from './routes/pages-n-links/catchall/$'
import { Route as PagesNLinksAppSettingsRouteImport } from './routes/pages-n-links/app/settings'
import { Route as PagesNLinksGroupedInsideRouteImport } from './routes/pages-n-links/_grouped/inside'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectVsQueryIndexRoute = UseEffectVsQueryIndexRouteImport.update({
  id: '/useEffect-vs-query/',
  path: '/useEffect-vs-query/',
  getParentRoute: () => rootRouteImport,
} as any)
const SsrThreeWaysIndexRoute = SsrThreeWaysIndexRouteImport.update({
  id: '/ssr-three-ways/',
  path: '/ssr-three-ways/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNLinksIndexRoute = PagesNLinksIndexRouteImport.update({
  id: '/pages-n-links/',
  path: '/pages-n-links/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectVsQueryUseQueryRoute =
  UseEffectVsQueryUseQueryRouteImport.update({
    id: '/useEffect-vs-query/use-query',
    path: '/useEffect-vs-query/use-query',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseEffectVsQueryUseEffectRoute =
  UseEffectVsQueryUseEffectRouteImport.update({
    id: '/useEffect-vs-query/use-effect',
    path: '/useEffect-vs-query/use-effect',
    getParentRoute: () => rootRouteImport,
  } as any)
const SsrThreeWaysSsrTrueRoute = SsrThreeWaysSsrTrueRouteImport.update({
  id: '/ssr-three-ways/ssr-true',
  path: '/ssr-three-ways/ssr-true',
  getParentRoute: () => rootRouteImport,
} as any)
const SsrThreeWaysSsrFalseWorksRoute =
  SsrThreeWaysSsrFalseWorksRouteImport.update({
    id: '/ssr-three-ways/ssr-false-works',
    path: '/ssr-three-ways/ssr-false-works',
    getParentRoute: () => rootRouteImport,
  } as any)
const SsrThreeWaysSsrFalseRoute = SsrThreeWaysSsrFalseRouteImport.update({
  id: '/ssr-three-ways/ssr-false',
  path: '/ssr-three-ways/ssr-false',
  getParentRoute: () => rootRouteImport,
} as any)
const SsrThreeWaysSsrDataOnlyRoute = SsrThreeWaysSsrDataOnlyRouteImport.update({
  id: '/ssr-three-ways/ssr-data-only',
  path: '/ssr-three-ways/ssr-data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNLinksSearchRoute = PagesNLinksSearchRouteImport.update({
  id: '/pages-n-links/search',
  path: '/pages-n-links/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNLinksNormalRoute = PagesNLinksNormalRouteImport.update({
  id: '/pages-n-links/normal',
  path: '/pages-n-links/normal',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNLinksAppRouteRoute = PagesNLinksAppRouteRouteImport.update({
  id: '/pages-n-links/app',
  path: '/pages-n-links/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNLinksGroupedRouteRoute = PagesNLinksGroupedRouteRouteImport.update({
  id: '/pages-n-links/_grouped',
  path: '/pages-n-links',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNLinksAppIndexRoute = PagesNLinksAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesNLinksAppRouteRoute,
} as any)
const UseEffectVsQueryApiUsersRoute =
  UseEffectVsQueryApiUsersRouteImport.update({
    id: '/useEffect-vs-query/api/users',
    path: '/useEffect-vs-query/api/users',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesNLinksParamsExampleIdRoute =
  PagesNLinksParamsExampleIdRouteImport.update({
    id: '/pages-n-links/params/$exampleId',
    path: '/pages-n-links/params/$exampleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesNLinksCatchallSplatRoute =
  PagesNLinksCatchallSplatRouteImport.update({
    id: '/pages-n-links/catchall/$',
    path: '/pages-n-links/catchall/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesNLinksAppSettingsRoute = PagesNLinksAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PagesNLinksAppRouteRoute,
} as any)
const PagesNLinksGroupedInsideRoute =
  PagesNLinksGroupedInsideRouteImport.update({
    id: '/inside',
    path: '/inside',
    getParentRoute: () => PagesNLinksGroupedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pages-n-links': typeof PagesNLinksGroupedRouteRouteWithChildren
  '/pages-n-links/app': typeof PagesNLinksAppRouteRouteWithChildren
  '/pages-n-links/normal': typeof PagesNLinksNormalRoute
  '/pages-n-links/search': typeof PagesNLinksSearchRoute
  '/ssr-three-ways/ssr-data-only': typeof SsrThreeWaysSsrDataOnlyRoute
  '/ssr-three-ways/ssr-false': typeof SsrThreeWaysSsrFalseRoute
  '/ssr-three-ways/ssr-false-works': typeof SsrThreeWaysSsrFalseWorksRoute
  '/ssr-three-ways/ssr-true': typeof SsrThreeWaysSsrTrueRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/pages-n-links/': typeof PagesNLinksIndexRoute
  '/ssr-three-ways/': typeof SsrThreeWaysIndexRoute
  '/useEffect-vs-query/': typeof UseEffectVsQueryIndexRoute
  '/pages-n-links/inside': typeof PagesNLinksGroupedInsideRoute
  '/pages-n-links/app/settings': typeof PagesNLinksAppSettingsRoute
  '/pages-n-links/catchall/$': typeof PagesNLinksCatchallSplatRoute
  '/pages-n-links/params/$exampleId': typeof PagesNLinksParamsExampleIdRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
  '/pages-n-links/app/': typeof PagesNLinksAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pages-n-links': typeof PagesNLinksIndexRoute
  '/pages-n-links/normal': typeof PagesNLinksNormalRoute
  '/pages-n-links/search': typeof PagesNLinksSearchRoute
  '/ssr-three-ways/ssr-data-only': typeof SsrThreeWaysSsrDataOnlyRoute
  '/ssr-three-ways/ssr-false': typeof SsrThreeWaysSsrFalseRoute
  '/ssr-three-ways/ssr-false-works': typeof SsrThreeWaysSsrFalseWorksRoute
  '/ssr-three-ways/ssr-true': typeof SsrThreeWaysSsrTrueRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/ssr-three-ways': typeof SsrThreeWaysIndexRoute
  '/useEffect-vs-query': typeof UseEffectVsQueryIndexRoute
  '/pages-n-links/inside': typeof PagesNLinksGroupedInsideRoute
  '/pages-n-links/app/settings': typeof PagesNLinksAppSettingsRoute
  '/pages-n-links/catchall/$': typeof PagesNLinksCatchallSplatRoute
  '/pages-n-links/params/$exampleId': typeof PagesNLinksParamsExampleIdRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
  '/pages-n-links/app': typeof PagesNLinksAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pages-n-links/_grouped': typeof PagesNLinksGroupedRouteRouteWithChildren
  '/pages-n-links/app': typeof PagesNLinksAppRouteRouteWithChildren
  '/pages-n-links/normal': typeof PagesNLinksNormalRoute
  '/pages-n-links/search': typeof PagesNLinksSearchRoute
  '/ssr-three-ways/ssr-data-only': typeof SsrThreeWaysSsrDataOnlyRoute
  '/ssr-three-ways/ssr-false': typeof SsrThreeWaysSsrFalseRoute
  '/ssr-three-ways/ssr-false-works': typeof SsrThreeWaysSsrFalseWorksRoute
  '/ssr-three-ways/ssr-true': typeof SsrThreeWaysSsrTrueRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/pages-n-links/': typeof PagesNLinksIndexRoute
  '/ssr-three-ways/': typeof SsrThreeWaysIndexRoute
  '/useEffect-vs-query/': typeof UseEffectVsQueryIndexRoute
  '/pages-n-links/_grouped/inside': typeof PagesNLinksGroupedInsideRoute
  '/pages-n-links/app/settings': typeof PagesNLinksAppSettingsRoute
  '/pages-n-links/catchall/$': typeof PagesNLinksCatchallSplatRoute
  '/pages-n-links/params/$exampleId': typeof PagesNLinksParamsExampleIdRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
  '/pages-n-links/app/': typeof PagesNLinksAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/pages-n-links'
    | '/pages-n-links/app'
    | '/pages-n-links/normal'
    | '/pages-n-links/search'
    | '/ssr-three-ways/ssr-data-only'
    | '/ssr-three-ways/ssr-false'
    | '/ssr-three-ways/ssr-false-works'
    | '/ssr-three-ways/ssr-true'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/pages-n-links/'
    | '/ssr-three-ways/'
    | '/useEffect-vs-query/'
    | '/pages-n-links/inside'
    | '/pages-n-links/app/settings'
    | '/pages-n-links/catchall/$'
    | '/pages-n-links/params/$exampleId'
    | '/useEffect-vs-query/api/users'
    | '/pages-n-links/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/pages-n-links'
    | '/pages-n-links/normal'
    | '/pages-n-links/search'
    | '/ssr-three-ways/ssr-data-only'
    | '/ssr-three-ways/ssr-false'
    | '/ssr-three-ways/ssr-false-works'
    | '/ssr-three-ways/ssr-true'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/ssr-three-ways'
    | '/useEffect-vs-query'
    | '/pages-n-links/inside'
    | '/pages-n-links/app/settings'
    | '/pages-n-links/catchall/$'
    | '/pages-n-links/params/$exampleId'
    | '/useEffect-vs-query/api/users'
    | '/pages-n-links/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/pages-n-links/_grouped'
    | '/pages-n-links/app'
    | '/pages-n-links/normal'
    | '/pages-n-links/search'
    | '/ssr-three-ways/ssr-data-only'
    | '/ssr-three-ways/ssr-false'
    | '/ssr-three-ways/ssr-false-works'
    | '/ssr-three-ways/ssr-true'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/pages-n-links/'
    | '/ssr-three-ways/'
    | '/useEffect-vs-query/'
    | '/pages-n-links/_grouped/inside'
    | '/pages-n-links/app/settings'
    | '/pages-n-links/catchall/$'
    | '/pages-n-links/params/$exampleId'
    | '/useEffect-vs-query/api/users'
    | '/pages-n-links/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PagesNLinksGroupedRouteRoute: typeof PagesNLinksGroupedRouteRouteWithChildren
  PagesNLinksAppRouteRoute: typeof PagesNLinksAppRouteRouteWithChildren
  PagesNLinksNormalRoute: typeof PagesNLinksNormalRoute
  PagesNLinksSearchRoute: typeof PagesNLinksSearchRoute
  SsrThreeWaysSsrDataOnlyRoute: typeof SsrThreeWaysSsrDataOnlyRoute
  SsrThreeWaysSsrFalseRoute: typeof SsrThreeWaysSsrFalseRoute
  SsrThreeWaysSsrFalseWorksRoute: typeof SsrThreeWaysSsrFalseWorksRoute
  SsrThreeWaysSsrTrueRoute: typeof SsrThreeWaysSsrTrueRoute
  UseEffectVsQueryUseEffectRoute: typeof UseEffectVsQueryUseEffectRoute
  UseEffectVsQueryUseQueryRoute: typeof UseEffectVsQueryUseQueryRoute
  PagesNLinksIndexRoute: typeof PagesNLinksIndexRoute
  SsrThreeWaysIndexRoute: typeof SsrThreeWaysIndexRoute
  UseEffectVsQueryIndexRoute: typeof UseEffectVsQueryIndexRoute
  PagesNLinksCatchallSplatRoute: typeof PagesNLinksCatchallSplatRoute
  PagesNLinksParamsExampleIdRoute: typeof PagesNLinksParamsExampleIdRoute
  UseEffectVsQueryApiUsersRoute: typeof UseEffectVsQueryApiUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/': {
      id: '/useEffect-vs-query/'
      path: '/useEffect-vs-query'
      fullPath: '/useEffect-vs-query/'
      preLoaderRoute: typeof UseEffectVsQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr-three-ways/': {
      id: '/ssr-three-ways/'
      path: '/ssr-three-ways'
      fullPath: '/ssr-three-ways/'
      preLoaderRoute: typeof SsrThreeWaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/': {
      id: '/pages-n-links/'
      path: '/pages-n-links'
      fullPath: '/pages-n-links/'
      preLoaderRoute: typeof PagesNLinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/use-query': {
      id: '/useEffect-vs-query/use-query'
      path: '/useEffect-vs-query/use-query'
      fullPath: '/useEffect-vs-query/use-query'
      preLoaderRoute: typeof UseEffectVsQueryUseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/use-effect': {
      id: '/useEffect-vs-query/use-effect'
      path: '/useEffect-vs-query/use-effect'
      fullPath: '/useEffect-vs-query/use-effect'
      preLoaderRoute: typeof UseEffectVsQueryUseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr-three-ways/ssr-true': {
      id: '/ssr-three-ways/ssr-true'
      path: '/ssr-three-ways/ssr-true'
      fullPath: '/ssr-three-ways/ssr-true'
      preLoaderRoute: typeof SsrThreeWaysSsrTrueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr-three-ways/ssr-false-works': {
      id: '/ssr-three-ways/ssr-false-works'
      path: '/ssr-three-ways/ssr-false-works'
      fullPath: '/ssr-three-ways/ssr-false-works'
      preLoaderRoute: typeof SsrThreeWaysSsrFalseWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr-three-ways/ssr-false': {
      id: '/ssr-three-ways/ssr-false'
      path: '/ssr-three-ways/ssr-false'
      fullPath: '/ssr-three-ways/ssr-false'
      preLoaderRoute: typeof SsrThreeWaysSsrFalseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr-three-ways/ssr-data-only': {
      id: '/ssr-three-ways/ssr-data-only'
      path: '/ssr-three-ways/ssr-data-only'
      fullPath: '/ssr-three-ways/ssr-data-only'
      preLoaderRoute: typeof SsrThreeWaysSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/search': {
      id: '/pages-n-links/search'
      path: '/pages-n-links/search'
      fullPath: '/pages-n-links/search'
      preLoaderRoute: typeof PagesNLinksSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/normal': {
      id: '/pages-n-links/normal'
      path: '/pages-n-links/normal'
      fullPath: '/pages-n-links/normal'
      preLoaderRoute: typeof PagesNLinksNormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/app': {
      id: '/pages-n-links/app'
      path: '/pages-n-links/app'
      fullPath: '/pages-n-links/app'
      preLoaderRoute: typeof PagesNLinksAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/_grouped': {
      id: '/pages-n-links/_grouped'
      path: '/pages-n-links'
      fullPath: '/pages-n-links'
      preLoaderRoute: typeof PagesNLinksGroupedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/app/': {
      id: '/pages-n-links/app/'
      path: '/'
      fullPath: '/pages-n-links/app/'
      preLoaderRoute: typeof PagesNLinksAppIndexRouteImport
      parentRoute: typeof PagesNLinksAppRouteRoute
    }
    '/useEffect-vs-query/api/users': {
      id: '/useEffect-vs-query/api/users'
      path: '/useEffect-vs-query/api/users'
      fullPath: '/useEffect-vs-query/api/users'
      preLoaderRoute: typeof UseEffectVsQueryApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/params/$exampleId': {
      id: '/pages-n-links/params/$exampleId'
      path: '/pages-n-links/params/$exampleId'
      fullPath: '/pages-n-links/params/$exampleId'
      preLoaderRoute: typeof PagesNLinksParamsExampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/catchall/$': {
      id: '/pages-n-links/catchall/$'
      path: '/pages-n-links/catchall/$'
      fullPath: '/pages-n-links/catchall/$'
      preLoaderRoute: typeof PagesNLinksCatchallSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/app/settings': {
      id: '/pages-n-links/app/settings'
      path: '/settings'
      fullPath: '/pages-n-links/app/settings'
      preLoaderRoute: typeof PagesNLinksAppSettingsRouteImport
      parentRoute: typeof PagesNLinksAppRouteRoute
    }
    '/pages-n-links/_grouped/inside': {
      id: '/pages-n-links/_grouped/inside'
      path: '/inside'
      fullPath: '/pages-n-links/inside'
      preLoaderRoute: typeof PagesNLinksGroupedInsideRouteImport
      parentRoute: typeof PagesNLinksGroupedRouteRoute
    }
  }
}

interface PagesNLinksGroupedRouteRouteChildren {
  PagesNLinksGroupedInsideRoute: typeof PagesNLinksGroupedInsideRoute
}

const PagesNLinksGroupedRouteRouteChildren: PagesNLinksGroupedRouteRouteChildren =
  {
    PagesNLinksGroupedInsideRoute: PagesNLinksGroupedInsideRoute,
  }

const PagesNLinksGroupedRouteRouteWithChildren =
  PagesNLinksGroupedRouteRoute._addFileChildren(
    PagesNLinksGroupedRouteRouteChildren,
  )

interface PagesNLinksAppRouteRouteChildren {
  PagesNLinksAppSettingsRoute: typeof PagesNLinksAppSettingsRoute
  PagesNLinksAppIndexRoute: typeof PagesNLinksAppIndexRoute
}

const PagesNLinksAppRouteRouteChildren: PagesNLinksAppRouteRouteChildren = {
  PagesNLinksAppSettingsRoute: PagesNLinksAppSettingsRoute,
  PagesNLinksAppIndexRoute: PagesNLinksAppIndexRoute,
}

const PagesNLinksAppRouteRouteWithChildren =
  PagesNLinksAppRouteRoute._addFileChildren(PagesNLinksAppRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PagesNLinksGroupedRouteRoute: PagesNLinksGroupedRouteRouteWithChildren,
  PagesNLinksAppRouteRoute: PagesNLinksAppRouteRouteWithChildren,
  PagesNLinksNormalRoute: PagesNLinksNormalRoute,
  PagesNLinksSearchRoute: PagesNLinksSearchRoute,
  SsrThreeWaysSsrDataOnlyRoute: SsrThreeWaysSsrDataOnlyRoute,
  SsrThreeWaysSsrFalseRoute: SsrThreeWaysSsrFalseRoute,
  SsrThreeWaysSsrFalseWorksRoute: SsrThreeWaysSsrFalseWorksRoute,
  SsrThreeWaysSsrTrueRoute: SsrThreeWaysSsrTrueRoute,
  UseEffectVsQueryUseEffectRoute: UseEffectVsQueryUseEffectRoute,
  UseEffectVsQueryUseQueryRoute: UseEffectVsQueryUseQueryRoute,
  PagesNLinksIndexRoute: PagesNLinksIndexRoute,
  SsrThreeWaysIndexRoute: SsrThreeWaysIndexRoute,
  UseEffectVsQueryIndexRoute: UseEffectVsQueryIndexRoute,
  PagesNLinksCatchallSplatRoute: PagesNLinksCatchallSplatRoute,
  PagesNLinksParamsExampleIdRoute: PagesNLinksParamsExampleIdRoute,
  UseEffectVsQueryApiUsersRoute: UseEffectVsQueryApiUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
