/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseEffectVsQueryIndexRouteImport } from './routes/useEffect-vs-query/index'
import { Route as UseEffectVsQueryUseQueryRouteImport } from './routes/useEffect-vs-query/use-query'
import { Route as UseEffectVsQueryUseEffectRouteImport } from './routes/useEffect-vs-query/use-effect'
import { Route as UseEffectVsQueryApiUsersRouteImport } from './routes/useEffect-vs-query/api/users'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectVsQueryIndexRoute = UseEffectVsQueryIndexRouteImport.update({
  id: '/useEffect-vs-query/',
  path: '/useEffect-vs-query/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectVsQueryUseQueryRoute =
  UseEffectVsQueryUseQueryRouteImport.update({
    id: '/useEffect-vs-query/use-query',
    path: '/useEffect-vs-query/use-query',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseEffectVsQueryUseEffectRoute =
  UseEffectVsQueryUseEffectRouteImport.update({
    id: '/useEffect-vs-query/use-effect',
    path: '/useEffect-vs-query/use-effect',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseEffectVsQueryApiUsersRoute =
  UseEffectVsQueryApiUsersRouteImport.update({
    id: '/useEffect-vs-query/api/users',
    path: '/useEffect-vs-query/api/users',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/useEffect-vs-query/': typeof UseEffectVsQueryIndexRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/useEffect-vs-query': typeof UseEffectVsQueryIndexRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/useEffect-vs-query/': typeof UseEffectVsQueryIndexRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/useEffect-vs-query/'
    | '/useEffect-vs-query/api/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/useEffect-vs-query'
    | '/useEffect-vs-query/api/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/useEffect-vs-query/'
    | '/useEffect-vs-query/api/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UseEffectVsQueryUseEffectRoute: typeof UseEffectVsQueryUseEffectRoute
  UseEffectVsQueryUseQueryRoute: typeof UseEffectVsQueryUseQueryRoute
  UseEffectVsQueryIndexRoute: typeof UseEffectVsQueryIndexRoute
  UseEffectVsQueryApiUsersRoute: typeof UseEffectVsQueryApiUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/': {
      id: '/useEffect-vs-query/'
      path: '/useEffect-vs-query'
      fullPath: '/useEffect-vs-query/'
      preLoaderRoute: typeof UseEffectVsQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/use-query': {
      id: '/useEffect-vs-query/use-query'
      path: '/useEffect-vs-query/use-query'
      fullPath: '/useEffect-vs-query/use-query'
      preLoaderRoute: typeof UseEffectVsQueryUseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/use-effect': {
      id: '/useEffect-vs-query/use-effect'
      path: '/useEffect-vs-query/use-effect'
      fullPath: '/useEffect-vs-query/use-effect'
      preLoaderRoute: typeof UseEffectVsQueryUseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/api/users': {
      id: '/useEffect-vs-query/api/users'
      path: '/useEffect-vs-query/api/users'
      fullPath: '/useEffect-vs-query/api/users'
      preLoaderRoute: typeof UseEffectVsQueryApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UseEffectVsQueryUseEffectRoute: UseEffectVsQueryUseEffectRoute,
  UseEffectVsQueryUseQueryRoute: UseEffectVsQueryUseQueryRoute,
  UseEffectVsQueryIndexRoute: UseEffectVsQueryIndexRoute,
  UseEffectVsQueryApiUsersRoute: UseEffectVsQueryApiUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
