/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseEffectVsQueryIndexRouteImport } from './routes/useEffect-vs-query/index'
import { Route as PagesNLinksIndexRouteImport } from './routes/pages-n-links/index'
import { Route as UseEffectVsQueryUseQueryRouteImport } from './routes/useEffect-vs-query/use-query'
import { Route as UseEffectVsQueryUseEffectRouteImport } from './routes/useEffect-vs-query/use-effect'
import { Route as PagesNLinksNormalRouteImport } from './routes/pages-n-links.normal'
import { Route as PagesNLinksGroupedRouteRouteImport } from './routes/pages-n-links/_grouped/route'
import { Route as UseEffectVsQueryApiUsersRouteImport } from './routes/useEffect-vs-query/api/users'
import { Route as PagesNLinksParamsExampleIdRouteImport } from './routes/pages-n-links/params/$exampleId'
import { Route as PagesNLinksCatchallSplatRouteImport } from './routes/pages-n-links/catchall/$'
import { Route as PagesNLinksGroupedInsideRouteImport } from './routes/pages-n-links/_grouped/inside'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectVsQueryIndexRoute = UseEffectVsQueryIndexRouteImport.update({
  id: '/useEffect-vs-query/',
  path: '/useEffect-vs-query/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNLinksIndexRoute = PagesNLinksIndexRouteImport.update({
  id: '/pages-n-links/',
  path: '/pages-n-links/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectVsQueryUseQueryRoute =
  UseEffectVsQueryUseQueryRouteImport.update({
    id: '/useEffect-vs-query/use-query',
    path: '/useEffect-vs-query/use-query',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseEffectVsQueryUseEffectRoute =
  UseEffectVsQueryUseEffectRouteImport.update({
    id: '/useEffect-vs-query/use-effect',
    path: '/useEffect-vs-query/use-effect',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesNLinksNormalRoute = PagesNLinksNormalRouteImport.update({
  id: '/pages-n-links/normal',
  path: '/pages-n-links/normal',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNLinksGroupedRouteRoute = PagesNLinksGroupedRouteRouteImport.update({
  id: '/pages-n-links/_grouped',
  path: '/pages-n-links',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectVsQueryApiUsersRoute =
  UseEffectVsQueryApiUsersRouteImport.update({
    id: '/useEffect-vs-query/api/users',
    path: '/useEffect-vs-query/api/users',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesNLinksParamsExampleIdRoute =
  PagesNLinksParamsExampleIdRouteImport.update({
    id: '/pages-n-links/params/$exampleId',
    path: '/pages-n-links/params/$exampleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesNLinksCatchallSplatRoute =
  PagesNLinksCatchallSplatRouteImport.update({
    id: '/pages-n-links/catchall/$',
    path: '/pages-n-links/catchall/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesNLinksGroupedInsideRoute =
  PagesNLinksGroupedInsideRouteImport.update({
    id: '/inside',
    path: '/inside',
    getParentRoute: () => PagesNLinksGroupedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pages-n-links': typeof PagesNLinksGroupedRouteRouteWithChildren
  '/pages-n-links/normal': typeof PagesNLinksNormalRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/pages-n-links/': typeof PagesNLinksIndexRoute
  '/useEffect-vs-query/': typeof UseEffectVsQueryIndexRoute
  '/pages-n-links/inside': typeof PagesNLinksGroupedInsideRoute
  '/pages-n-links/catchall/$': typeof PagesNLinksCatchallSplatRoute
  '/pages-n-links/params/$exampleId': typeof PagesNLinksParamsExampleIdRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pages-n-links': typeof PagesNLinksIndexRoute
  '/pages-n-links/normal': typeof PagesNLinksNormalRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/useEffect-vs-query': typeof UseEffectVsQueryIndexRoute
  '/pages-n-links/inside': typeof PagesNLinksGroupedInsideRoute
  '/pages-n-links/catchall/$': typeof PagesNLinksCatchallSplatRoute
  '/pages-n-links/params/$exampleId': typeof PagesNLinksParamsExampleIdRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pages-n-links/_grouped': typeof PagesNLinksGroupedRouteRouteWithChildren
  '/pages-n-links/normal': typeof PagesNLinksNormalRoute
  '/useEffect-vs-query/use-effect': typeof UseEffectVsQueryUseEffectRoute
  '/useEffect-vs-query/use-query': typeof UseEffectVsQueryUseQueryRoute
  '/pages-n-links/': typeof PagesNLinksIndexRoute
  '/useEffect-vs-query/': typeof UseEffectVsQueryIndexRoute
  '/pages-n-links/_grouped/inside': typeof PagesNLinksGroupedInsideRoute
  '/pages-n-links/catchall/$': typeof PagesNLinksCatchallSplatRoute
  '/pages-n-links/params/$exampleId': typeof PagesNLinksParamsExampleIdRoute
  '/useEffect-vs-query/api/users': typeof UseEffectVsQueryApiUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/pages-n-links'
    | '/pages-n-links/normal'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/pages-n-links/'
    | '/useEffect-vs-query/'
    | '/pages-n-links/inside'
    | '/pages-n-links/catchall/$'
    | '/pages-n-links/params/$exampleId'
    | '/useEffect-vs-query/api/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/pages-n-links'
    | '/pages-n-links/normal'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/useEffect-vs-query'
    | '/pages-n-links/inside'
    | '/pages-n-links/catchall/$'
    | '/pages-n-links/params/$exampleId'
    | '/useEffect-vs-query/api/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/pages-n-links/_grouped'
    | '/pages-n-links/normal'
    | '/useEffect-vs-query/use-effect'
    | '/useEffect-vs-query/use-query'
    | '/pages-n-links/'
    | '/useEffect-vs-query/'
    | '/pages-n-links/_grouped/inside'
    | '/pages-n-links/catchall/$'
    | '/pages-n-links/params/$exampleId'
    | '/useEffect-vs-query/api/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PagesNLinksGroupedRouteRoute: typeof PagesNLinksGroupedRouteRouteWithChildren
  PagesNLinksNormalRoute: typeof PagesNLinksNormalRoute
  UseEffectVsQueryUseEffectRoute: typeof UseEffectVsQueryUseEffectRoute
  UseEffectVsQueryUseQueryRoute: typeof UseEffectVsQueryUseQueryRoute
  PagesNLinksIndexRoute: typeof PagesNLinksIndexRoute
  UseEffectVsQueryIndexRoute: typeof UseEffectVsQueryIndexRoute
  PagesNLinksCatchallSplatRoute: typeof PagesNLinksCatchallSplatRoute
  PagesNLinksParamsExampleIdRoute: typeof PagesNLinksParamsExampleIdRoute
  UseEffectVsQueryApiUsersRoute: typeof UseEffectVsQueryApiUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/': {
      id: '/useEffect-vs-query/'
      path: '/useEffect-vs-query'
      fullPath: '/useEffect-vs-query/'
      preLoaderRoute: typeof UseEffectVsQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/': {
      id: '/pages-n-links/'
      path: '/pages-n-links'
      fullPath: '/pages-n-links/'
      preLoaderRoute: typeof PagesNLinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/use-query': {
      id: '/useEffect-vs-query/use-query'
      path: '/useEffect-vs-query/use-query'
      fullPath: '/useEffect-vs-query/use-query'
      preLoaderRoute: typeof UseEffectVsQueryUseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/use-effect': {
      id: '/useEffect-vs-query/use-effect'
      path: '/useEffect-vs-query/use-effect'
      fullPath: '/useEffect-vs-query/use-effect'
      preLoaderRoute: typeof UseEffectVsQueryUseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/normal': {
      id: '/pages-n-links/normal'
      path: '/pages-n-links/normal'
      fullPath: '/pages-n-links/normal'
      preLoaderRoute: typeof PagesNLinksNormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/_grouped': {
      id: '/pages-n-links/_grouped'
      path: '/pages-n-links'
      fullPath: '/pages-n-links'
      preLoaderRoute: typeof PagesNLinksGroupedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useEffect-vs-query/api/users': {
      id: '/useEffect-vs-query/api/users'
      path: '/useEffect-vs-query/api/users'
      fullPath: '/useEffect-vs-query/api/users'
      preLoaderRoute: typeof UseEffectVsQueryApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/params/$exampleId': {
      id: '/pages-n-links/params/$exampleId'
      path: '/pages-n-links/params/$exampleId'
      fullPath: '/pages-n-links/params/$exampleId'
      preLoaderRoute: typeof PagesNLinksParamsExampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/catchall/$': {
      id: '/pages-n-links/catchall/$'
      path: '/pages-n-links/catchall/$'
      fullPath: '/pages-n-links/catchall/$'
      preLoaderRoute: typeof PagesNLinksCatchallSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-n-links/_grouped/inside': {
      id: '/pages-n-links/_grouped/inside'
      path: '/inside'
      fullPath: '/pages-n-links/inside'
      preLoaderRoute: typeof PagesNLinksGroupedInsideRouteImport
      parentRoute: typeof PagesNLinksGroupedRouteRoute
    }
  }
}

interface PagesNLinksGroupedRouteRouteChildren {
  PagesNLinksGroupedInsideRoute: typeof PagesNLinksGroupedInsideRoute
}

const PagesNLinksGroupedRouteRouteChildren: PagesNLinksGroupedRouteRouteChildren =
  {
    PagesNLinksGroupedInsideRoute: PagesNLinksGroupedInsideRoute,
  }

const PagesNLinksGroupedRouteRouteWithChildren =
  PagesNLinksGroupedRouteRoute._addFileChildren(
    PagesNLinksGroupedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PagesNLinksGroupedRouteRoute: PagesNLinksGroupedRouteRouteWithChildren,
  PagesNLinksNormalRoute: PagesNLinksNormalRoute,
  UseEffectVsQueryUseEffectRoute: UseEffectVsQueryUseEffectRoute,
  UseEffectVsQueryUseQueryRoute: UseEffectVsQueryUseQueryRoute,
  PagesNLinksIndexRoute: PagesNLinksIndexRoute,
  UseEffectVsQueryIndexRoute: UseEffectVsQueryIndexRoute,
  PagesNLinksCatchallSplatRoute: PagesNLinksCatchallSplatRoute,
  PagesNLinksParamsExampleIdRoute: PagesNLinksParamsExampleIdRoute,
  UseEffectVsQueryApiUsersRoute: UseEffectVsQueryApiUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
